// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/search-vehicles.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function supabaseAnon() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}

// src/lib/mcp/tools/search-vehicles.ts
var search_vehicles_default = defineTool({
  name: "search_vehicles",
  title: "Buscar ve\xEDculos",
  description: "Busca an\xFAncios de ve\xEDculos aprovados no Z\xE9 do Rolo. Filtre por texto livre, categoria, cidade/UF e faixa de pre\xE7o. Retorna at\xE9 20 resultados com id, t\xEDtulo, marca, modelo, ano, pre\xE7o, cidade e UF.",
  inputSchema: {
    query: z.string().optional().describe("Texto livre (marca, modelo, palavras-chave)."),
    category: z.string().optional().describe("Categoria: carros, motos, caminhoes, onibus, vans, tratores, implementos."),
    city: z.string().optional().describe("Cidade."),
    state: z.string().optional().describe("Sigla do estado (UF), ex: SP, PR."),
    min_price: z.number().optional().describe("Pre\xE7o m\xEDnimo em BRL."),
    max_price: z.number().optional().describe("Pre\xE7o m\xE1ximo em BRL."),
    limit: z.number().int().min(1).max(20).optional().describe("Quantidade de resultados (padr\xE3o 10, m\xE1x 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input) => {
    let q = supabaseAnon().from("vehicles").select("id, title, brand, model, year, price, city, state, category, status").eq("status", "approved").limit(input.limit ?? 10);
    if (input.query) q = q.or(`title.ilike.%${input.query}%,brand.ilike.%${input.query}%,model.ilike.%${input.query}%`);
    if (input.category) q = q.eq("category", input.category);
    if (input.city) q = q.ilike("city", `%${input.city}%`);
    if (input.state) q = q.eq("state", input.state.toUpperCase());
    if (typeof input.min_price === "number") q = q.gte("price", input.min_price);
    if (typeof input.max_price === "number") q = q.lte("price", input.max_price);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-vehicle.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_vehicle_default = defineTool2({
  name: "get_vehicle",
  title: "Detalhes do ve\xEDculo",
  description: "Retorna todos os detalhes de um an\xFAncio de ve\xEDculo aprovado pelo id.",
  inputSchema: {
    id: z2.string().uuid().describe("ID (UUID) do ve\xEDculo.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const { data, error } = await supabaseAnon().from("vehicles").select("*").eq("id", id).eq("status", "approved").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Ve\xEDculo n\xE3o encontrado." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { vehicle: data }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "ze-do-rolo-mcp",
  title: "Z\xE9 do Rolo",
  version: "0.1.0",
  instructions: "Ferramentas para navegar no cat\xE1logo p\xFAblico do Z\xE9 do Rolo \u2014 marketplace brasileiro de ve\xEDculos (carros, motos, caminh\xF5es, tratores, \xF4nibus, vans, implementos). Use search_vehicles para descobrir an\xFAncios por marca/modelo/cidade/pre\xE7o e get_vehicle para detalhes completos.",
  tools: [search_vehicles_default, get_vehicle_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
